Add simple ads support in helm and doi menu
jkitchin/org-ref pull request #797
Opened 2020-09-24 00:01 UTC by alejandrogallo

I think `org-ref` lacks ADS support,
since it can do many things that `WOS` can and can be used
without an academic account.

Sadly I don't know exactly how many menus `org-ref`
has, if someone hints me the way to go I can do it,
or maybe someone can also contribute to this PR.

Basically it works like this
given the doi

```
10.1016/0375-9601(74)90283-7
```

we can jump to ads by browsing

```
https://ui.adsabs.harvard.edu/abs/%22{doi}%22
```

ADS works with bibcodes (to my regret), and using the
bibcode one can go to 

- [ ] citing articles
  ```
  https://ui.adsabs.harvard.edu/abs/{bibcode}/citations
  ```
- [ ] References
  ```
  https://ui.adsabs.harvard.edu/abs/{bibcode}/references
  ```
- [ ] Similar
  ```
  https://ui.adsabs.harvard.edu/abs/{bibcode}/similar
  ```

However for some reason this does not work with the `{doi}`
because the first GET request to the previously defined ads
url basically redirects to the correspondent url with the bibcode,
i.e.

```
https://ui.adsabs.harvard.edu/abs/%22{doi}%22
```

redirects to

```
https://ui.adsabs.harvard.edu/abs/{bibcode}
```

and trying to do
```
https://ui.adsabs.harvard.edu/abs/%22{doi}%22/citations
```
is futile.

Therefore maybe we could write a function that
uses ADS to get the bibcode and use the bibcode
to do the get requests.

Therefore this pull request should strive to do the following:

- [ ] Write a doi to bibcode function.
- [ ] Add ads to all menus
- [ ] Create citations function and add it to menus
- [ ] Create references function and add it to menus
- [ ] Create similar function and add it to menus

2020-09-26 18:06 UTC, jkitchin requested changes

2020-09-26 18:06 UTC, jkitchin commented on org-ref-helm-cite.el
> +              ("Related articles in ADS" . org-ref-ads-related-at-point)
is org-ref-ads-related-at-point defined somewhere? I don't see it here.

2020-09-27 16:19 UTC, alejandrogallo commented on org-ref-helm-cite.el
> +              ("Related articles in ADS" . org-ref-ads-related-at-point)
You're of course right, I implemented a test function for it and then
I forgot to remove it, sorry for that.
I removed it now.

2020-09-27 16:25 UTC, alejandrogallo commented
I was thinking now that it's probably not worth it going to such great lengths
to implement
the `citations`, `references` and `similar` links in ads, since the new ads UI
is so easy and fool proof.

If you're ok with it I'd suggest just adding basic ads support
to jump to the paper's page, i.e., just using with the doi
`10.1016/0375-9601(74)90283-7`

the followint url

https://ui.adsabs.harvard.edu/abs/%2210.1016/0375-9601(74)90283-7%22

which works fine and then the user can just click at `citations`,
`references` and `similar`.
This is basically what is done now in [papis](https://github.com/papis/papis).

The only thing I'd need to know is where I should implement the other
menus, right now is for

- [X] Helm
- [ ] Hydra
- [ ] Simple menu

but since I'm quite new to `org-ref` I don't know which other menus are there.
And then this pull request would be complete.

2020-10-02 15:14 UTC, merged